In [15]:
import nltk
from nltk.stem import PorterStemmer , WordNetLemmatizer
from nltk.corpus import wordnet

In [16]:
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [17]:
words = [
    "running", "runs", "ran", "studies", "studying",
    "better", "best", "cars", "children", "mice",
    "flying", "flies", "went", "playing", "played",
    "happier", "happiness"
]

In [18]:
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

In [19]:
for word in words:
  stem = stemmer.stem(word)
  lemma = lemmatizer.lemmatize(word)
  print(f"{word} | {stem} | {lemma}")

running | run | running
runs | run | run
ran | ran | ran
studies | studi | study
studying | studi | studying
better | better | better
best | best | best
cars | car | car
children | children | child
mice | mice | mouse
flying | fli | flying
flies | fli | fly
went | went | went
playing | play | playing
played | play | played
happier | happier | happier
happiness | happi | happiness


In [20]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [24]:
sentence = "This is a simple example to show how stopwords are removed from a sentence"
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [25]:
words = nltk.word_tokenize(sentence.lower())


In [26]:
stop_words = set(stopwords.words('english'))

In [27]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [29]:
filterd_words = [word for word in words if word not in stop_words]

In [30]:
words

['this',
 'is',
 'a',
 'simple',
 'example',
 'to',
 'show',
 'how',
 'stopwords',
 'are',
 'removed',
 'from',
 'a',
 'sentence']

In [31]:
filterd_words

['simple', 'example', 'show', 'stopwords', 'removed', 'sentence']

In [3]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [4]:
sentences = [
    "love movie",
    "movie great",
    "hate movie",
    "movie terrible",
    "love great acting",
    "hate terrible acting"
]

In [5]:
vocab = sorted(set(" ".join(sentences).split()))

In [6]:
vocab

['acting', 'great', 'hate', 'love', 'movie', 'terrible']

In [9]:
#this will convert a word to vector and this multiple words vector will create a matrix

import numpy as np
onehot = OneHotEncoder()
onehot.fit(np.array(vocab).reshape(-1,1))



OneHotEncoder()

In [11]:
for s in sentences:
  words = s.split()
  sentence_matrix = onehot.transform(np.array(words).reshape(-1,1))
  print(sentence_matrix)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2 stored elements and shape (2, 6)>
  Coords	Values
  (0, 3)	1.0
  (1, 4)	1.0
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2 stored elements and shape (2, 6)>
  Coords	Values
  (0, 4)	1.0
  (1, 1)	1.0
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2 stored elements and shape (2, 6)>
  Coords	Values
  (0, 2)	1.0
  (1, 4)	1.0
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2 stored elements and shape (2, 6)>
  Coords	Values
  (0, 4)	1.0
  (1, 5)	1.0
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3 stored elements and shape (3, 6)>
  Coords	Values
  (0, 3)	1.0
  (1, 1)	1.0
  (2, 0)	1.0
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3 stored elements and shape (3, 6)>
  Coords	Values
  (0, 2)	1.0
  (1, 5)	1.0
  (2, 0)	1.0


In [12]:
#Sentences --> vectors
#Bag of words
bow = CountVectorizer()
bow_matrix = bow.fit_transform(sentences)


In [15]:
print(bow.get_feature_names_out())

['acting' 'great' 'hate' 'love' 'movie' 'terrible']


In [18]:
print(bow_matrix.toarray())

[[0 0 0 1 1 0]
 [0 1 0 0 1 0]
 [0 0 1 0 1 0]
 [0 0 0 0 1 1]
 [1 1 0 1 0 0]
 [1 0 1 0 0 1]]


In [19]:
tfidf = TfidfVectorizer(vocabulary=vocab)
tfidf_matrix = tfidf.fit_transform(sentences)

In [20]:
print(tfidf.get_feature_names_out())

['acting' 'great' 'hate' 'love' 'movie' 'terrible']


In [22]:
print(tfidf_matrix.toarray())

[[0.         0.         0.         0.81019752 0.58615696 0.        ]
 [0.         0.81019752 0.         0.         0.58615696 0.        ]
 [0.         0.         0.81019752 0.         0.58615696 0.        ]
 [0.         0.         0.         0.         0.58615696 0.81019752]
 [0.57735027 0.57735027 0.         0.57735027 0.         0.        ]
 [0.57735027 0.         0.57735027 0.         0.         0.57735027]]
